before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Same repo deployment
brews:
  - github:
        owner: applegreengrape
        name: finnhub-terminal
    folder: Formula
    homepage: https://github.com/applegreengrape/finnhub-terminal
    description: terminal dashboard for finnhub.io