builds:
  - binary: starling-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archive:
  replacements:
    darwin: macOS
    386: 32-bit
    amd64: 64-bit
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
      
# Same repo deployment
brews:
  - github:
        owner: applegreengrape
        name: finnhub-terminal
    folder: Formula
    homepage: https://github.com/applegreengrape/finnhub-terminal
    description: terminal dashboard for finnhub.io