brews:
  - github:
        owner: applegreengrape
        name: finnhub-terminal
    folder: Formula
    homepage: https://github.com/applegreengrape/finnhub-terminal
    description: A simple description of your application.