# This file was generated by GoReleaser. DO NOT EDIT.
class FinnhubTerminal < Formula
  desc "terminal dashboard for finnhub.io"
  homepage "https://github.com/applegreengrape/finnhub-terminal"
  version "0.1.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/applegreengrape/finnhub-terminal/releases/download/v0.1.9/finnhub-terminal_0.1.9_Darwin_x86_64.tar.gz"
    sha256 "d2883aa2997a409af588113ba66c31183716b2a2e40a6d72537f24691e7b4ab4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/applegreengrape/finnhub-terminal/releases/download/v0.1.9/finnhub-terminal_0.1.9_Linux_x86_64.tar.gz"
      sha256 "21279b6d4950fc30f5ae2839f5b6671bd7eb3f1b038ae698dd3fce8ce776c3bf"
    end
  end

  def install
    bin.install "finnhub-terminal"
  end
end
