# This file was generated by GoReleaser. DO NOT EDIT.
class FinnhubTerminal < Formula
  desc "A simple description of your application."
  homepage "https://github.com/applegreengrape/finnhub-terminal"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/applegreengrape/finnhub-terminal/releases/download/v0.1.4/finnhub-terminal_0.1.4_darwin_amd64.tar.gz"
    sha256 "f0761f6e3427517779824db1d1b45eb3bb92e6c6208106bfdb9e340549215299"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/applegreengrape/finnhub-terminal/releases/download/v0.1.4/finnhub-terminal_0.1.4_linux_amd64.tar.gz"
      sha256 "3de12c0e39ce0fef062b950ed5b5b993528d832b902e8678ec4f73eb59da8e92"
    end
  end

  def install
    bin.install "finnhub-terminal"
  end
end
